FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

# Not needed as we are using docker compose to reference files and folders in the container image from the pwd.
COPY . .

CMD ["npm", "run", "start"]